"""Exact mathematical core for Prospect's active-acquisition experiment."""

from bench.active_acquisition.oracle import (
    ExactAcquisitionEvaluation,
    ExactOracleDecision,
    FractionOracle,
)
from bench.active_acquisition.policies import (
    AcquisitionPolicyDecision,
    ActionScore,
    eig_only,
    goal_only,
    oracle,
    prospect_voi,
    raw_entropy,
    shuffled_information,
    uniform_random,
)
from bench.active_acquisition.problem import (
    ACQUISITION_ACTIONS,
    NONCANDIDATE_SIGN_INVARIANCE_ACTIONS,
    NUISANCE_SCAN,
    OVERPOWERED_NEGATIVE,
    OVERPOWERED_POSITIVE,
    SKIP,
    STRONG_NEGATIVE,
    STRONG_POSITIVE,
    TERMINAL_ACTIONS,
    WEAK_NEGATIVE,
    WEAK_POSITIVE,
    AcquisitionAction,
    AcquisitionDiagnostics,
    AcquisitionKind,
    AcquisitionResult,
    ActuatorRegime,
    HiddenActuatorProblem,
    TerminalAction,
    TerminalResult,
)

__all__ = (
    "ACQUISITION_ACTIONS",
    "NONCANDIDATE_SIGN_INVARIANCE_ACTIONS",
    "NUISANCE_SCAN",
    "OVERPOWERED_NEGATIVE",
    "OVERPOWERED_POSITIVE",
    "SKIP",
    "STRONG_NEGATIVE",
    "STRONG_POSITIVE",
    "TERMINAL_ACTIONS",
    "WEAK_NEGATIVE",
    "WEAK_POSITIVE",
    "ActionScore",
    "AcquisitionAction",
    "AcquisitionDiagnostics",
    "AcquisitionKind",
    "AcquisitionPolicyDecision",
    "AcquisitionResult",
    "ActuatorRegime",
    "ExactAcquisitionEvaluation",
    "ExactOracleDecision",
    "FractionOracle",
    "HiddenActuatorProblem",
    "TerminalAction",
    "TerminalResult",
    "eig_only",
    "goal_only",
    "oracle",
    "prospect_voi",
    "raw_entropy",
    "shuffled_information",
    "uniform_random",
)
